import type { NextPage } from 'next';
import Head from 'next/head';
import { useEffect, useState } from 'react';

const Home: NextPage = () => {
  const [items, setItems] = useState<{ pais: string; capital: string; continente: string }[]>([]);

  useEffect(() => {
    fetch('/api/hello')
      .then((response) => response.json())
      .then((data) => setItems(data));
  }, []);

  return (
    <div>
      <Head>
        <title>NextJS with Puppeteer</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main>
        <h1>NextJS with Puppeteer</h1>
        <table>
          {items.map(({ continente, pais, capital }) => (
            <tr key={`${continente}-${pais}-${capital}`}>
              <td>{continente}</td>
              <td>{pais}</td>
              <td>{capital}</td>
            </tr>
          ))}
        </table>
      </main>
    </div>
  );
};

export default Home;
