import type { NextPage } from 'next';
import Head from 'next/head';
import { useEffect, useState } from 'react';

const Home: NextPage = () => {
  const [items, setItems] = useState([]);

  useEffect(() => {
    fetch('/api/hello')
      .then((response) => response.json())
      .then((data) => setItems(data));
  }, []);

  return (
    <div>
      <Head>
        <title>NextJS with Puppeteer</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main>
        <h1>NextJS with Puppeteer</h1>
        <ul>
          {items.map(({ name }) => (<li key={name}>{name}</li>))}
        </ul>
      </main>
    </div>
  );
};

export default Home;
